# This file relates to internal XMOS infrastructure and should be ignored by external users

lib_name: lib_otpinfo
project: '{{lib_name}}'
title: '{{lib_name}}: OTP reading library'
version: 2.2.1

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  root_doc: doc/rst/lib_otpinfo.rst
  cognidox_part_number: XM-006391-UG
  doxygen_projects:
    lib_ethernet:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_otpinfo.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-007519-SM
